name: hireme
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  #Firebase
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13

  #Design
  stylish_bottom_bar: ^0.1.2
  persistent_bottom_nav_bar: ^4.0.2
  google_fonts: ^3.0.1
  awesome_dialog: ^2.2.1
  lottie: ^1.3.0

 # StateManagement
  provider: ^6.0.2
  form_field_validator: ^1.1.0
  go_router: ^3.1.0
  
  #Database
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  oktoast: ^3.2.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/