name: hrms
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #Firebase
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13

  #Design
  stylish_bottom_bar: ^0.1.2
  animated_toggle_switch: ^0.5.2
  google_fonts: ^2.3.2
  animated_splash_screen: ^1.2.0
  awesome_dialog: ^2.2.1

 # StateManagement
  provider: ^6.0.2
  form_field_validator: ^1.1.0
  
  #Database
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  go_router: ^3.1.0
  page_transition: ^2.0.5

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/